### ISSUE TITLE
Mods repository system

### ISSUE THREAD

**Issue by parruda** [gotta-dev/gotta-mod#3]
It would be great if we had a way to publish, discover and install the mods created by users. The following is a proposal for a simple system to allow that.

## Example mod metadata file

```yaml
# mod.yml
name: my-mod

version: 0.1.0

authors:
  - John Doe <john.doe@example.com>

source:
  github: username/repo/path
  branch: (optional)
  tag: (optional)

dependencies:
  - another-mod1
  - another-mod2
```

## Registering a mod
To register a mod, first you need to have the mod metadata properly set in `mod.yml`. Then you run.
```
$ cd my-mod
my-mod$ gotta register mod
```
This command will upload the mod metadata to an API that will then be used to guide the search and install commands.

## Searching for a mod
The search will just hit an API and search through the metadata and return the results.

```
project$ gotta search mod my-mod
my-mod - The mod description
```

## Installing a mod
To install a mod, the CLI will hit an API and download the metadata for the mod, grab the github repo and clone it inside the `mods` directory.
```
project$ gotta install mod my-mod
```
